# Dia 1

## Episodio 1 - Fundamentos de Python

#### Variável 
Qualquer intérprete Python pode ser usado como uma calculadora:

In [8]:
# Soma e multiplicação
3 + 5 * 4

23

In [9]:
# guarda valor no objeto 'weight_kg'
weight_kg = 60

Obs.: A partir de agora, sempre que usarmos **weight_kg**, o Python substituirá o valor que atribuímos a ele. Nos termos leigo, uma variável é um nome para um valor.

##### Tipos de dados
Python conhece vários tipos de dados. Três comuns são:

* números inteiros
* números de ponto flutuante
* cordas.

In [10]:
# Ponto flutuante
weight_kg = 60.0

In [16]:
# String
weight_kg_text = 'weight em Kilograma:'

##### Usando variáveis em Python

In [17]:
print(weight_kg)

60.0


In [18]:
print(weight_kg_text, weight_kg)

weight em Kilograma: 60.0


In [19]:
print('weight em Libra:', 2.2 * weight_kg)

weight em Libra: 132.0


In [20]:
print(weight_kg)

60.0


Obs.: Para alterar o valor da weight_kgvariável, precisamos atribuir weight_kg um novo valor usando o =sinal de igual:

In [22]:
weight_kg = 65.0
print('weight em kilograma agora:', weight_kg)

weight em kilograma agora: 65.0


In [23]:
# Existem 2,2 libras por quilograma
weight_lb = 2.2 * weight_kg
print(weight_kg_text, weight_kg, 'e em libra:', weight_lb)

weight em Kilograma: 65.0 e em libra: 143.0


In [25]:
weight_kg = 100.0
print('weight em kilograma agora:', weight_kg, 'e weight em libras ainda é:', weight_lb)

weight em kilograma agora: 100.0 e weight em libras ainda é: 143.0


### Exercicíos

* Quais valores as variáveis mass e age possuem após cada comando no programa abaixo?

In [2]:
mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20
print(mass, age)

95.0 102


* O que o programa a seguir imprime

In [6]:
first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)

Hopper Grace


###### Finalizado a primeira parte...

## Episodio 2 - Analisando dados do paciente

#### Rodando dados no Python - careegando libs
Para começar a processar dados de inflamação, precisamos carregá-los no Python. Podemos fazer isso usando uma biblioteca chamada NumPy,

In [43]:
import numpy
# ou import numpy is np

In [28]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [30]:
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [31]:
print(type(data))

<class 'numpy.ndarray'>


In [32]:
# Data Type
print(data.dtype)

float64


In [33]:
print(data.shape)

(60, 40)


In [34]:
print('first value in data:', data[0, 0])

first value in data: 0.0


In [36]:
print('middle value in data:', data[30, 20])
    

middle value in data: 13.0


##### Cortando dados
Um índice como [30, 20] seleciona um único elemento de uma matriz, mas também podemos selecionar seções inteiras.

In [37]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [38]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [39]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


####  Analisando dados
O NumPy possui várias funções úteis que usam uma matriz como entrada para executar operações em seus valores.

In [40]:
print(numpy.mean(data))

6.14875


Obs.: Nem todas as funções têm entrada
* Geralmente, uma função usa entradas para produzir saídas. No entanto, algumas funções produzem saídas sem precisar de nenhuma entrada.

In [41]:
import time
print(time.ctime())

Thu Jun 25 23:01:42 2020


* fim do primeiro dia